neo4j-graphql/neo4j-graphql-java

- pom.xml
- src/main/kotlin/org/neo4j/graphql/CrudOperations.kt
- src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt
- src/main/kotlin/org/neo4j/graphql/Predicates.kt
- src/main/kotlin/org/neo4j/graphql/Translator.kt
- src/test/kotlin/org/neo4j/graphql/AugmentationTest.kt
- src/test/kotlin/org/neo4j/graphql/CypherDirectiveTest.kt
- src/test/kotlin/org/neo4j/graphql/TranslatorTest.kt
- src/test/resources/movies-test-schema.graphql
* upgrade to latest graphql version -> added generics on Type
* improve implementation of schema augmentation - lists are now immutable so have to be recreated and reset
* directives are added to schema as schema validation is now much stricter
* preventing _id duplicates in query params
* declare relation direction as enum
* fixes on tests
(Note this is reopen PR as the previous was raised from master not feature branch, thus picking up too many changes)
> Update to graphql-java v12

- readme.adoc
In "@relationship on Types" changed "start" and "end" to "from" and "to"
> Fix readme mis-information

- src/main/kotlin/org/neo4j/graphql/CrudOperations.kt
- src/main/kotlin/org/neo4j/graphql/Translator.kt
- src/test/kotlin/org/neo4j/graphql/AugmentationTest.kt
- src/test/resources/movie-test.md
Fixes #19 
Add merge operation only if the type has an ID to merge on.
> fixes #19: add merge operation

- src/main/kotlin/org/neo4j/graphql/ExtensionFunctions.kt
- src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt
- src/main/kotlin/org/neo4j/graphql/Neo4jTypes.kt
- src/main/kotlin/org/neo4j/graphql/Translator.kt
- src/test/kotlin/org/neo4j/graphql/MovieSchemaTest.kt
- src/test/kotlin/org/neo4j/graphql/TckTest.kt
- src/test/resources/movie-test.md
- src/test/resources/movies-test-schema.graphql
List of provided changes:
- Renamed `TemporalTypes` into `Neo4jTypes` so we can easily add the support for Point values and reuse the same logic
- Implemented the support to the Date types for queries and mutations
> fixes #10: support date/time

- readme.adoc
- src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt
- src/main/kotlin/org/neo4j/graphql/Predicates.kt
- src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt
- src/main/kotlin/org/neo4j/graphql/handler/CreateTypeHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/DeleteHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- src/main/kotlin/org/neo4j/graphql/handler/relation/BaseRelationHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationTypeHandler.kt
- src/test/resources/augmentation-tests.adoc
- src/test/resources/filter-tests.adoc
- src/test/resources/movie-tests.adoc
- src/test/resources/translator-tests1.adoc
> 5. Add support for native (database) Ids

- src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt
- src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt
- src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- src/test/resources/movie-tests.adoc
- src/test/resources/translator-tests1.adoc
> 6. Add support for parameters for skip / limit

- src/main/kotlin/org/neo4j/graphql/Predicates.kt
- src/test/resources/filter-tests.adoc
> Append operand name in filter expressions

- readme.adoc
Related to my question in issue #100 I think these minor changes would have enabled me to figured out how to do what I wanted without having to look at the source code.
> Make it clearer the BOTH is an option for the relation direction

- docs/Server.groovy
Updated sample groovy server with basic logger and Neo4j 4.x diver
> update sample groovy server

- src/main/kotlin/org/neo4j/graphql/Predicates.kt
- src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt
- src/test/resources/filter-tests.adoc
Fix filter issue when using the same Operator on the same Field twice
resolves #113
> Fix filter issue when using the same Operator on the same Field twice

- src/main/kotlin/org/neo4j/graphql/Translator.kt
- src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt
- src/test/resources/filter-tests.adoc
> Add ability to use a variable as filter.

- src/main/kotlin/org/neo4j/graphql/AugmentationHandler.kt
- src/main/kotlin/org/neo4j/graphql/BuildingEnv.kt
- src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt
- src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt
- src/main/kotlin/org/neo4j/graphql/handler/CreateTypeHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/DeleteHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/relation/BaseRelationHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationTypeHandler.kt
- src/main/kotlin/org/neo4j/graphql/handler/relation/DeleteRelationHandler.kt
- src/test/kotlin/org/neo4j/graphql/AugmentationTests.kt
- src/test/resources/schema-operations-tests.adoc
> Consider customized top-level type names

- pom.xml
- src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt
- src/main/resources/lib_directives.graphql
- src/main/resources/neo4j_types.graphql
- src/test/kotlin/com/intellij/rt/execution/junit/FileComparisonFailure.java
- src/test/kotlin/org/neo4j/graphql/AugmentationTests.kt
- src/test/kotlin/org/neo4j/graphql/CypherTests.kt
- src/test/kotlin/org/neo4j/graphql/TranslatorExceptionTests.kt
- src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt
- src/test/kotlin/org/neo4j/graphql/utils/CypherTestSuite.kt
- src/test/kotlin/org/neo4j/graphql/utils/GraphQLSchemaTestSuite.kt
- src/test/resources/custom-fields.adoc
- src/test/resources/filter-tests.adoc
Since adapting the tests may take a lot of time, I have adapted our test framework to provide a diff to the test case definition, in case a test fails.
Furthermore I added the possibility for integration tests.
resolves #137
> Improve test framework to update tests with newly generated data

- core/src/main/kotlin/org/neo4j/graphql/Predicates.kt
- core/src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt
- core/src/test/resources/filter-tests.adoc
> Merge fix from 1.0 into master

- core/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt
- core/src/main/kotlin/org/neo4j/graphql/SchemaConfig.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/CreateTypeHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/DeleteHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationTypeHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/relation/DeleteRelationHandler.kt
- core/src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt
- core/src/test/kotlin/org/neo4j/graphql/utils/CypherTestSuite.kt
- core/src/test/resources/custom-fields.adoc
- core/src/test/resources/movie-tests.adoc
- core/src/test/resources/schema-operations-tests.adoc
> Make the capitalization of the Query-Type fields configurable

- core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcherForContainer.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/CreateTypeHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/DeleteHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/relation/BaseRelationHandler.kt
- core/src/test/kotlin/org/neo4j/graphql/IssuesTests.kt
- core/src/test/kotlin/org/neo4j/graphql/utils/CypherTestSuite.kt
- core/src/test/resources/issues/gh-85.adoc
> add support for cypher directive with scalar result

- core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- core/src/test/kotlin/org/neo4j/graphql/IssuesTests.kt
- core/src/test/resources/cypher-directive-tests.adoc
- core/src/test/resources/issues/gh-147.adoc
- core/src/test/resources/movie-tests.adoc
> fix filtering on directive in combination with filtering on type field

- core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt
- core/src/test/kotlin/org/neo4j/graphql/IssuesTests.kt
- core/src/test/resources/issues/gh-149.adoc
> allow OptimizationStrategy FILTER_AS_MATCH to be used without filter

- core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- core/src/test/resources/issues/gh-163.adoc
> Allow optimized FILTER_AS_MATCH strategy to be used with simple filtering

- .run/Run All tests including integration tests.run.xml
- core/src/test/kotlin/org/neo4j/graphql/IssuesTests.kt
- core/src/test/resources/issues/gh-65.adoc
The reported bug is already fixed
> Add test case for #65.

- core/src/main/kotlin/org/neo4j/graphql/parser/QueryParser.kt
- core/src/test/resources/filter-tests.adoc
- core/src/test/resources/issues/gh-27.adoc
- core/src/test/resources/optimized-query-for-filter.adoc
> Use existential sub-queries

- core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- core/src/main/kotlin/org/neo4j/graphql/parser/QueryParser.kt
- core/src/test/resources/filter-tests.adoc
- core/src/test/resources/issues/gh-47.adoc
> Support filtering of null values also via variables

- .gitignore
- examples/graphql-spring-boot/pom.xml
- examples/graphql-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/graphqlspringboot/config/GraphQLConfiguration.kt
- examples/graphql-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/graphqlspringboot/controller/AdditionalQueries.kt
- examples/graphql-spring-boot/src/test/kotlin/org/neo4j/graphql/examples/graphqlspringboot/controller/QueriesIT.kt
- pom.xml
> Updated versions and .gitignore

- examples/dgs-spring-boot/pom.xml
- examples/dgs-spring-boot/readme.adoc
- examples/dgs-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/dgsspringboot/config/GraphQLConfiguration.kt
- examples/dgs-spring-boot/src/test/kotlin/org/neo4j/graphql/examples/dgsspringboot/datafetcher/AdditionalDataFetcherTest.kt
- neo4j-graphql-augmented-schema-generator-maven-plugin/pom.xml
- neo4j-graphql-augmented-schema-generator-maven-plugin/src/main/kotlin/org/neo4j/graphql/augmented_schema_generator/plugin/AugmentedSchemaGeneratorMojo.kt
- pom.xml
- readme.adoc
This will allow the use of a type save graphql API.
> Add a maven plugin to generate the augmented schema

- core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
- core/src/test/resources/translator-tests3.adoc
This fix ensures that sorting relational fields will work correctly
> Fix sorting of relations

- core/pom.xml
- core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt
- core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
> upgrade to cypher-dsl 2023.0.0

- core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcherForContainer.kt
- core/src/test/resources/issues/gh-299-incorrect-mutation-translation-for-IDs-with-property-aliases.adoc
Fixes: https://github.com/neo4j-graphql/neo4j-graphql-java/issues/299
Successfully ran `mvn clean install` with new tests
> Fix Issue #299 mutation translation for IDs with @property
