pom.xml, src/main/kotlin/org/neo4j/graphql/CrudOperations.kt, src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, src/main/kotlin/org/neo4j/graphql/Predicates.kt, src/main/kotlin/org/neo4j/graphql/Translator.kt, src/test/kotlin/org/neo4j/graphql/AugmentationTest.kt, src/test/kotlin/org/neo4j/graphql/CypherDirectiveTest.kt, src/test/kotlin/org/neo4j/graphql/TranslatorTest.kt, src/test/resources/movies-test-schema.graphql
Note at this point it is a partial fix for issue #22 + corresponding tests (failing)
The original issue (direction of cypher relation) has now been fixed and translator takes into account direction of relation where both types on the relation are the same.
However, this fix has uncovered another issue - the generated cypher does not actually work and that is due to the fact that two different names of node are used. For example, a generated query looks as follows:
```
MATCH (user:User) WHERE user.name = $userName 
RETURN user { .name,
referredBy:[(user)-[userReferredBy:REFERRED_BY]->(userReferredByReferredBy:User) | userReferredBy { .referralDate,referredBy:userReferredByReferredBy { .name } }][0],
referred:[(user)<-[userReferred:REFERRED_BY]-(userReferredUser:User) | userReferred { …
```
=> Bugfix for issue#22 - relation with same types does not generate correct cypher

src/main/kotlin/org/neo4j/graphql/CrudOperations.kt, src/main/kotlin/org/neo4j/graphql/ExtensionFunctions.kt, src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, src/main/kotlin/org/neo4j/graphql/Translator.kt, src/test/kotlin/org/neo4j/graphql/AugmentationTest.kt, src/test/kotlin/org/neo4j/graphql/TckTest.kt, src/test/resources/movie-test.md, src/test/resources/movies-test-schema.graphql
Added auto-generated mutation support for relationships.
Given the following schema:
```
type Movie { id:ID!, publishedBy: Publisher }
type Publisher { name:ID! }
```
we create these two mutations:
```
addMoviePublishedBy(id:ID!, publishedBy:ID!) : Movie
deleteMoviePublishedBy(id:ID!, publishedBy:ID!) : Movie
```
=> fixes #26: Support Mutations for Relationships

pom.xml, readme.adoc, src/main/kotlin/org/neo4j/graphql/QueryContext.kt, src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt, src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, src/test/resources/augmentation-tests.adoc, src/test/resources/movie-tests.adoc, src/test/resources/translator-tests1.adoc
add support for interfaces (resolves #4)
merge after #50 #49
=> 4. Add support for interfaces

src/main/kotlin/org/neo4j/graphql/Predicates.kt, src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt, src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt
Since graphql submits IDs as strings, they need to get converted for native ID references
=> fix string handling for native ID

src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt, src/test/resources/dynamic-property-tests.adoc
We forgot to pass the id, when updating a node. This causes the id to be unset.
This PR resolves #95
=> Fixes the issue that an update removes the custom ID field on the node

pom.xml, readme.adoc, src/main/kotlin/org/neo4j/cypherdsl/core/PassThrough.kt, src/main/kotlin/org/neo4j/graphql/BuildingEnv.kt, src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, src/main/kotlin/org/neo4j/graphql/Neo4jTypes.kt, src/main/kotlin/org/neo4j/graphql/Predicates.kt, src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt, src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, src/main/kotlin/org/neo4j/opencypherdsl/DslExtensions.kt, src/main/resources/neo4j.graphql, src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt, src/test/resources/augmentation-tests.adoc, src/test/resources/filter-tests.adoc, src/test/resources/optimized-query-for-filter.adoc, src/test/resources/translator-tests1.adoc
This PR add support for [spatials](https://neo4j.com/docs/cypher-manual/3.5/syntax/spatial/#cypher-spatial-crs-geographic) and [distance comparisons](https://neo4j.com/docs/cypher-manual/3.5/functions/spatial/#functions-distance).
Now you can rund queries like:
```graphql
query {
person(location:{longitude: 1, latitude: 2 }){
name
location {
crs
longitude
latitude
height
}
}
}
```
or 
```graphql
{
person(filter:{ location_distance_gte: { distance: 3, point: {longitude: 1, latitude:2, height: 3}}}){
name
}
}
```
resolves #11
=> Add support for spatial point values and distance comparisons

pom.xml, readme.adoc, src/main/kotlin/org/neo4j/graphql/NoOpCoercing.kt, src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt, src/test/kotlin/org/neo4j/graphql/CypherTests.kt, src/test/resources/translator-tests-custom-scalars.adoc
This PR add support for custom scalars
For the given schema:
```graphql
scalar Date
type Movie {
_id: ID!
title: String!
released: Date
}
```
you can now run queries like:
```graphql
{
movie(filter:{released_gte: 1994}) {
title
released
}
}
```
resolves #9
=> Add support for custom scalars

src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationHandler.kt, src/main/kotlin/org/neo4j/graphql/handler/relation/DeleteRelationHandler.kt, src/test/kotlin/org/neo4j/graphql/CypherTests.kt, src/test/resources/movie-tests.adoc, src/test/resources/relationship-tests.adoc
This bugfix solves the problem that the mapping was wrong for incoming relations
(resolves #98)
=> Fix for relationship mutations are not using the correct direction

src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt, src/test/resources/dynamic-property-tests.adoc, src/test/resources/movie-tests.adoc, src/test/resources/translator-tests-custom-scalars.adoc
Now we always use `SET x += {}` to update properties.
fixes #105
=> This change fixes an issue where properties got unset for when updating a node

src/test/resources/relationship-tests.adoc
=> Add missing test for rich relations where both ends are of same type

src/test/kotlin/org/neo4j/graphql/utils/CypherTestSuite.kt
AS requested by https://github.com/neo4j-graphql/neo4j-graphql-java/pull/114#issuecomment-683479125
=> Add ability to print out additional debug information for cypher-tests

src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, src/test/resources/relationship-tests.adoc, src/test/resources/translator-tests1.adoc
```graphql
{
player{
id
memberships {
team {
id
}
prop
}
}
}
```
was mapped to
```cypher
MATCH (player: Player)
RETURN player {
.id,
memberships: [(player)<-[playerMemberships: MEMBER_OF]-(playerMembershipsPlayer: Player) | playerMemberships {
team: playerMembershipsPlayer { .id },
.prop
}]
} AS player
```
but
```cypher
MATCH (player: Player)
RETURN player {
.id,
memberships: [(player)-[playerMemberships: MEMBER_OF]->(playerMembershipsTeam: Team) | playerMemberships {
team: playerMembershipsTeam { .id },
.prop
}]
} AS player
```
is expected
=> This bugfix solves a problem where inverse relationships were incorrectly mapped

core/pom.xml
this update contains a bugfix where the renderer causes stackoverflow exceptions:
https://github.com/neo4j-contrib/cypher-dsl/pull/149
=> update to current version of neo4j-cypher-dsl

core/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/main/kotlin/org/neo4j/graphql/handler/relation/BaseRelationHandler.kt, core/src/test/resources/issues/gh-170.adoc, core/src/test/resources/movie-tests.adoc
=> allow projection starting query from rich relationship

core/src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/test/resources/augmentation-tests.adoc, core/src/test/resources/issues/gh-169.adoc, core/src/test/resources/movie-tests.adoc
=> Use default values for sorting and paging on fields

core/src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcherForContainer.kt, core/src/main/kotlin/org/neo4j/graphql/handler/CreateTypeHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/DeleteHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/main/kotlin/org/neo4j/graphql/handler/relation/BaseRelationHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/relation/CreateRelationTypeHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/relation/DeleteRelationHandler.kt, core/src/main/kotlin/org/neo4j/graphql/parser/QueryParser.kt
=> Add missing JavaDoc

core/pom.xml, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt, core/src/test/kotlin/DataFetcherInterceptorDemo.kt, core/src/test/kotlin/GraphQLServer.kt, core/src/test/kotlin/org/neo4j/graphql/utils/AsciiDocTestSuite.kt, core/src/test/kotlin/org/neo4j/graphql/utils/CypherTestSuite.kt, core/src/test/resources/custom-fields.adoc, core/src/test/resources/filter-tests.adoc, examples/graphql-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/graphqlspringboot/config/Neo4jConfiguration.kt, pom.xml
this requires also an update to java 11
additionally I cleaned up the dependencies
=> update to neo4j 4.2

core/src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt, core/src/test/resources/augmentation-tests.adoc, core/src/test/resources/issues/gh-170.adoc
If the field of GraphQL Type maps to an *..n relation (a list) and there is currently no `filter`-argument defined, we now generate it in the augmented schema.
The logic for handling these nested filters is already implementd, so no further code-adjustments are required.
resolves #129
=> Augment filter argument for nested fields

.github/workflows/pr-build.yaml, core/src/test/kotlin/org/neo4j/graphql/CypherTests.kt, core/src/test/kotlin/org/neo4j/graphql/utils/CypherTestSuite.kt, core/src/test/resources/filter-tests.adoc, core/src/test/resources/issues/gh-112.adoc, core/src/test/resources/issues/gh-147.adoc
With this change, integration tests will route calls directly through the GraphQL API and not just to the translator. Thus we can find potential errors in the return values faster.
=> Run integration tests through the GraphQL API

core/src/main/kotlin/org/neo4j/graphql/DirectiveConstants.kt, core/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, core/src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/main/resources/lib_directives.graphql, core/src/test/resources/cypher-directive-tests.adoc, core/src/test/resources/issues/gh-190-cypher-directive-with-passThrough.adoc, readme.adoc
The new argument `passThrough` of the `@cypher` directive allows the user to return an arbitrary result for the directive
resolves #190
=> Add support for the passThrough argument of the cypher directive.

core/src/main/kotlin/org/neo4j/graphql/BuildingEnv.kt, core/src/main/kotlin/org/neo4j/graphql/SchemaBuilder.kt, core/src/main/kotlin/org/neo4j/graphql/SchemaConfig.kt, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcherForContainer.kt, core/src/main/kotlin/org/neo4j/graphql/handler/CypherDirectiveHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/main/kotlin/org/neo4j/graphql/parser/QueryParser.kt, core/src/main/resources/neo4j_types.graphql, core/src/test/kotlin/org/neo4j/graphql/AugmentationTests.kt, core/src/test/kotlin/org/neo4j/graphql/CypherTests.kt, core/src/test/kotlin/org/neo4j/graphql/utils/GraphQLSchemaTestSuite.kt, core/src/test/resources/tck-test-files/cypher/pagination.adoc, core/src/test/resources/tck-test-files/cypher/sort.adoc, core/src/test/resources/tck-test-files/schema/relationship.adoc, core/src/test/resources/tck-test-files/schema/simple.adoc, readme.adoc
This feature is part of migrating our API to the one generated by `@neo4j/graphql`.
Here we move the fields for paging and sorting into a options input type, which can be passed to queries and projected relational fields
resolves #196
=> Separate sorting and paging into own input type

core/pom.xml, core/src/main/kotlin/org/neo4j/graphql/BuildingEnv.kt, core/src/main/kotlin/org/neo4j/graphql/SchemaConfig.kt, core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, core/src/test/resources/tck-test-files/cypher/pagination.adoc, core/src/test/resources/tck-test-files/cypher/sort.adoc, core/src/test/resources/tck-test-files/schema/relationship.adoc, core/src/test/resources/tck-test-files/schema/simple.adoc
=> Generate plural names for augmented fields and types

core/src/main/kotlin/org/neo4j/graphql/parser/QueryParser.kt, core/src/test/resources/issues/gh-210.adoc
=> Allow to filter relation by interface

core/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, core/src/main/kotlin/org/neo4j/graphql/Neo4jTypes.kt, core/src/main/kotlin/org/neo4j/graphql/Predicates.kt, core/src/main/kotlin/org/neo4j/graphql/SchemaConfig.kt, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcherForContainer.kt, core/src/main/kotlin/org/neo4j/graphql/handler/filter/OptimizedFilterHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/main/kotlin/org/neo4j/graphql/parser/QueryParser.kt, core/src/main/resources/neo4j_types.graphql, core/src/test/kotlin/org/neo4j/graphql/utils/GraphQLSchemaTestSuite.kt, core/src/test/resources/tck-test-files/cypher/types/datetime.adoc, core/src/test/resources/tck-test-files/schema/types/datetime.adoc
With these changes a new configuration param `useTemporalScalars` was introduced. With this configuration enabled, neo4js' temporales like `Date`, `Time`, `LocalTime`, `DateTime` and `LocalDateTime` are used as scalars (strings).
resolves #223
resolves #109
resolves #108
resolves #93
=> Use scalars for temporal types

core/src/main/kotlin/org/neo4j/graphql/AugmentationHandler.kt, core/src/main/kotlin/org/neo4j/graphql/Cypher.kt, core/src/main/kotlin/org/neo4j/graphql/DynamicProperties.kt, core/src/main/kotlin/org/neo4j/graphql/InvalidQueryException.kt, core/src/main/kotlin/org/neo4j/graphql/Translator.kt, core/src/main/kotlin/org/neo4j/graphql/handler/AugmentFieldHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt, core/src/main/kotlin/org/neo4j/graphql/handler/MergeOrUpdateHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/test/kotlin/org/neo4j/graphql/TranslatorExceptionTests.kt, core/src/test/resources/augmentation-tests.adoc, core/src/test/resources/cypher-directive-tests.adoc, core/src/test/resources/movie-tests.adoc, core/src/test/resources/schema-operations-tests.adoc, core/src/test/resources/tck-test-files/schema/directives/ignore.adoc, core/src/test/resources/translator-tests1.adoc
Using the graphql infrastructure for parsing the request ensures that:
* the request is compliant with the schema
* internally we can rely on `DataFetchingEnvironment` being correctly initialized
=> Use graphql infrastructure to parse requests

core/pom.xml, examples/dgs-spring-boot/pom.xml, examples/graphql-spring-boot/pom.xml, neo4j-graphql-augmented-schema-generator-maven-plugin/pom.xml, pom.xml
`neo4j-logging` shaded Log4j2 which is subject to CVE-2021-44228. Since we use it only in the test scope, it is safe to remove this dependency as long as all tests are still green.
resolves #260
=> Remove dependency for neo4j-logging in our tests

.github/workflows/pr-build.yaml, core/pom.xml, core/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, core/src/main/kotlin/org/neo4j/graphql/QueryContext.kt, core/src/main/kotlin/org/neo4j/graphql/Translator.kt, core/src/main/kotlin/org/neo4j/graphql/handler/BaseDataFetcher.kt, core/src/main/kotlin/org/neo4j/graphql/handler/QueryHandler.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/test/kotlin/DataFetcherInterceptorDemo.kt, core/src/test/kotlin/GraphQLServer.kt, core/src/test/resources/filter-tests.adoc, core/src/test/resources/optimized-query-for-filter.adoc, examples/dgs-spring-boot/pom.xml, examples/dgs-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/dgsspringboot/config/Neo4jConfiguration.kt, examples/graphql-kotlin-spring-boot/pom.xml, examples/graphql-kotlin-spring-boot/src/main/kotlin/org/neo4j/graphql/examples/graphqlspringboot/config/Neo4jConfiguration.kt, examples/graphql-spring-boot/pom.xml, examples/graphql-spring-boot/src/main/java/org/neo4j/graphql/examples/graphqlspringboot/config/Neo4jConfiguration.java, pom.xml, readme.adoc
=> Add support for neo4j 5.x

core/src/main/kotlin/org/neo4j/graphql/AugmentationHandler.kt, core/src/main/kotlin/org/neo4j/graphql/GraphQLExtensions.kt, core/src/main/kotlin/org/neo4j/graphql/Predicates.kt, core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/test/resources/augmentation-tests.adoc, core/src/test/resources/filter-tests.adoc, core/src/test/resources/tck-test-files/schema/types/arrays.adoc
This PR adds support for filters which can be used with list type properties of Node or Relation.
Filters added are: `INCLUDES_ANY`, `INCLUDES_ALL`, `NOT_INCLUDES`.
This PR is in reference with the PR of cypher-dsl library (https://github.com/neo4j-contrib/cypher-dsl/pull/374) which includes enhancement for list filters in that library. 
Test cases are included for all the code changes implemented.
=> Adding support for list type property filters

core/src/main/kotlin/org/neo4j/graphql/handler/projection/ProjectionBase.kt, core/src/test/resources/issues/gh-295-wrong-target-node-alias.adoc
This bugfix fixes an issue where the name of the end-node of a relation is not correctly used in the where clause
resolves #295
=> Fix wrong node name used for projection where on relation
